const dictionary = [
  ["a","a"],
  ["add","add, addition"],
  ["ainii","any"],
  ["Amikka","America, the United States"],
  ["and","and"],
  ["andrstan","understand"],
  ["aniwœn","anyone"],
  ["arro","air"],
  ["arroflia","plane, aeroplane"],
  ["arss","arse, bottom"],
  ["azol","apple"],
  ["azonom","astronomy"],

  ["bagir","bag, backpack"],
  ["bai","bye, goodbye"],
  ["bakk","back (informal)"],
  ["band","music band"],
  ["bas","pass"],
  ["basik","basic"],
  ["bii","be"],
  ["biolot","biology"],
  ["blonat","planet"],
  ["blœ","blue"],
  ["Boddist","Buddhist"],
  ["Bodisnatzrs","Bodysnatchers (band)"],
  ["bost","burst"],
  ["bœk","back"],
  ["Britia","Britain"],
  ["Britiz","British"],
  ["bro","bro"],
  ["brœd","bread"],
  ["bwas","place, location"],

  ["dai","day"],
  ["dat","that"],
  ["dho", "but, though, although"],
  ["di","the"],
  ["did","did"],
  ["dira","ten"],
  ["diksonri","dictionary"],
  ["dis","this"],
  ["dizital","digital"],
  ["do","do"],
  ["dodd","jump"],
  ["dog","dog"],
  ["donn","down"],
  ["dos","two"],
  ["drink","drink"],

  ["faarr","far"],
  ["fiind","friend"],
  ["fim","five"],
  ["fisi","body, physical"],
  ["fisiks","physics"],
  ["flaim","fire, flame"],
  ["flia","fly"],
  ["fliat","flight"],
  ["fokos","focus"],
  ["fol","multiply, -fold"],
  ["fon","phone"],
  ["fostiwit","festival"],
  ["for","for"],
  ["fœr","four"],
  ["from","from"],
  ["fridom","freedom"],
  ["frœk","frog"],

  ["gako","nine"],
  ["gaii","gay, lesbian (informal)"],
  ["gais","guys"],
  ["gali","hundred"],
  ["gamm","game"],
  ["gati","gay, lesbian (formal)"],
  ["giid","guide"],
  ["git","get, bring"],
  ["gœdidag","good day"],
  ["gœdimorgin","good morning"],
  ["gœdisiz","good night"],
  ["gœlli","LGBTQ+"],
  ["gratol","grateful, thankful"],
  ["grœ","grow"],

  ["haab","have"],
  ["habibi","friend"],
  ["hallœ","hello"],
  ["hai","hi"],
  ["haos","house"],
  ["haz","him"],
  ["hiirr","here"],
  ["hiiz","his"],
  ["hiz","he"],
  ["hobiz","happy"],
  ["hobisiz","happiness"],
  ["hosi", "use, using"],
  ["hœ","how"],

  ["i","I"],
  ["id","it"],
  ["if","if"],
  ["iiti","eight"],
  ["ik","I'm"],
  ["ikonos","economy"],
  ["ikonoset","economic"],
  ["iksban","expand"],
  ["iksit","excite"],
  ["iksitid","excited"],
  ["iksimit","excitement"],
  ["ikt","eat"],
  ["imii","me, my, myself"],
  ["in","in"],
  ["indizandis","independence (informal)"],
  ["Inland","England"],
  ["Inlish","English"],
  ["innowi","innovation"],
  ["intirnaizono","international"],
  ["is","is"],
  ["ist","is (alt)"],
  ["issra","independent"],
  ["isst","east"],
  ["issranis","independence"],
  ["it","it"],
  ["itoldai","yesterday"],
  ["itt","eat"],
  ["iz","its"],

  ["labt","laptop"],
  ["laii","lie"],
  ["lah","yes"],
  ["lasœksan","congratulations"],
  ["le","the (less common)"],
  ["Kabo","Cambodia"],
  ["kal","call"],
  ["kammo","camp"],
  ["kan","night"],
  ["Kanaada","Canada"],
  ["kimistri","chemistry"],
  ["kobkradd","frog"],
  ["kold","cold"],
  ["kommbotar","computer"],
  ["kommbotat","computation, computational"],
  ["konna","gonna"],
  ["kontinœ","continue"],
  ["kontinœli","continuous"],
  ["kontis","contest"],
  ["korri","curry"],
  ["korrot","correction"],
  ["kœll","cool"],
  ["Kristian","Christian"],
  ["krosi","nearby"],

  ["liif","life"],
  ["liik","like"],
  ["ligind","legend"],
  ["ligindo","legendary"],
  ["liwisi","revision"],
  ["low","low, little"],
  ["lowin","reduce"],
  ["loz","love"],

  ["maazik","magic"],
  ["maazikal","magical"],
  ["math","math"],
  ["mathi","mathematical"],
  ["mathi narizbikkolim","prestigious mathematical olympiad"],
  ["mi","question indicator"],
  ["mian","mean"],
  ["midt","meet"],
  ["midttaab","meetup"],
  ["midwi","middle"],
  ["midwidai","midday"],
  ["midwikan","midnight"],
  ["mika","cloud"],
  ["milk","milk"],
  ["Mislim","Islam, Muslim"],
  ["mobilfon","smartphone"],
  ["monniz","money"],
  ["mœrnin","morning"],

  ["nai","no, not"],
  ["naifol","divide"],
  ["naigi","negative"],
  ["naiwi","black"],
  ["narizbikk","prestigious"],
  ["narizbikkolim","prestigious contest"],
  ["nasœksan","enjoyable"],
  ["naizon","nation"],
  ["naizono","national"],
  ["NGL","not gonna lie"],
  ["niida","need"],
  ["nidi","subtract"],
  ["niw","new"],
  ["niwbi","newbie"],
  ["NKL","not gonna lie"],
  ["nol","none"],
  ["nott","north"],

  ["ob","up"],
  ["od","old"],
  ["of","of"],
  ["ok","okay"],
  ["okaii","okay"],
  ["oktaldai","day before yesterday"],
  ["olimmna","Olympics"],
  ["ond","and"],
  ["onn","on"],
  ["orwiti","orbit"],
  ["ot","or"],
  ["otdat", "update"],
  ["otdatid","updated"],
  ["ottimmo","utmost"],

  ["radi","red"],
  ["radiz","radish"],
  ["rados","radius"],
  ["riliks","relax"],
  ["rilozi","religion"],
  ["rirondai","day after tomorrow"],
  ["risti","rest"],
  ["risz","rizz (singular)"],
  ["riiwo","revolve"],
  ["riwisi","revision"],
  ["rizbik","respect"],
  ["robzil","picture"],
  ["rondai","tomorrow"],
  ["rœn","tree"],

  ["Saandai","Sunday"],
  ["saats","south"],
  ["sai", "say, tell"],
  ["saio","left"],
  ["salo","right"],
  ["samad","smart"],
  ["samid","summit"],
  ["Satirndai","Saturday"],
  ["saz","her"],
  ["shatin","chatting"],
  ["sid","she"],
  ["siid","hers"],
  ["siiz","science"],
  ["siizi","scientific"],
  ["siiz narizbikk olimmna","prestigious science olympiad"],
  ["sikma","sigma"],
  ["siks","six"],
  ["siks-sion","six seven (slang)"],
  ["Singabora","Singapore"],
  ["sion","seven"],
  ["siro","zero"],
  ["sitmir","statement"],
  ["skœl","school"],
  ["snatz","snatch"],
  ["snazr","snatcher"],
  ["sord","sorry"],
  ["sœitar","super"],
  ["sœksana","merry"],
  ["sœt","should"],
  ["star","star"],
  ["stato","statue"],
  ["stil","still"],
  ["stillwassir","still water"],
  ["ston","stone"],

  ["tabfon","tablet"],
  ["takk","take"],
  ["tamminno","million"],
  ["tanno","thousand"],
  ["taz","them"],
  ["tiim", "team, group"],
  ["tirbrik","relieved"],
  ["Tirr","Earth"],
  ["tisti","exam"],
  ["Thailand","Thailand"],
  ["thikk","thick"],
  ["tishir","teacher"],
  ["ti","yes"],
  ["tiz","they"],
  ["tiiz","theirs"],
  ["to","to"],
  ["toldai","today"],
  ["tri","three"],

  ["wii","we"],
  ["wiid","wide"],
  ["wiir","wire"],
  ["wiirnai","wireless"],
  ["wik","week"],
  ["wikiin","weekend"],
  ["win","win"],
  ["wirsin","version"],
  ["wœ", "you"],
  ["wœn","one"],
  ["want","want"],
  ["was","what"],
  ["wassir","water"],
  ["wisst","west"],
  ["wit","white"],
  ["witt","with"],
  ["wiz","hope"],
  ["wizif","hopeful"],
  ["woniit","unite"],
  ["woniiti","unity"],

  ["za","yes"],
  ["zad","them (non-binary)"],
  ["zam","charm"],
  ["zas","just"],
  ["zamœl","jamal"],
  ["zamœlin","jamaling"],
  ["Zamœlis","Jamalese"],
  ["zid","they (non-binary)"],
  ["ziid","their (non-binary)"],
  ["zill","chill"],
  ["zilod","yellow"]
];
