const dictionary = [
  ["a","a"],
  ["add","add, addition"],
  ["ainii","any"],
  ["Aksnat", "Uranus"],
  ["Amikka","America, the United States"],
  ["and","and"],
  ["andrstan","understand"],
  ["aniwœn","anyone"],
  ["arro","air"],
  ["arroflia","plane, aeroplane"],
  ["arss","arse, bottom"],
  ["azol","apple"],
  ["azonom","astronomy"],

  ["bagir","bag, backpack"],
  ["bai","bye, goodbye"],
  ["bakk","back (informal)"],
  ["band","music band"],
  ["bas","pass"],
  ["basik","basic"],
  ["bii","be"],
  ["bila", "time"],
  ["biolot","biology"],
  ["blit", "panel, plate"],
  ["blonat","planet"],
  ["Bloto", "Pluto"],
  ["blœ","blue"],
  ["Boddist","Buddhist"],
  ["Bodisnatzrs","Bodysnatchers (band)"],
  ["bost","burst"],
  ["bœk","back"],
  ["Britia","Britain"],
  ["Britiz","British"],
  ["bro","bro"],
  ["brœd","bread"],
  ["bwas","place, location"],

  ["Dabizil", "December"],
  ["dai","day"],
  ["daiz", "dice, die"],
  ["dat","that"],
  ["Deffil", "February"],
  ["dho", "but, though, although"],
  ["di","the"],
  ["did","did"],
  ["diist", "road, street"],
  ["diist agiz", "highway"],
  ["diist traan", "alley"],
  ["din", "then"],
  ["dir", "there"],
  ["dira","ten"],
  ["diksonri","dictionary"],
  ["dis","this"],
  ["dizital","digital"],
  ["do","do"],
  ["dodd","jump"],
  ["dog","dog"],
  ["donn","down"],
  ["dos","two"],
  ["drink","drink"],

  ["faarr","far"],
  ["fafa", "enough, sufficient"],
  ["fiind","friend"],
  ["fim","five"],
  ["fisi","body, physical"],
  ["fisiks","physics"],
  ["flaim","fire, flame"],
  ["Flanat", "Venus"],
  ["flia","fly"],
  ["fliat","flight"],
  ["fokos","focus"],
  ["fol","multiply, -fold"],
  ["fon","phone"],
  ["fostiwit","festival"],
  ["fotbol", "football (soccer)"],
  ["for","for"],
  ["fœr","four"],
  ["Fœkil", "August"],
  ["from","from"],
  ["fridom","freedom"],
  ["frœk","frog"],

  ["gako","nine"],
  ["gaii","gay, lesbian (informal)"],
  ["gais","guys"],
  ["gali","hundred"],
  ["gamm","game"],
  ["gati","gay, lesbian (formal)"],
  ["giid","guide"],
  ["Giinat", "Saturn"],
  ["git","get, bring"],
  ["gœdidag","good day"],
  ["gœdimorgin","good morning"],
  ["gœdisiz","good night"],
  ["gœlli","LGBTQ+"],
  ["gratol","grateful, thankful"],
  ["grœ","grow"],

  ["haab","have"],
  ["habibi","friend"],
  ["hallœ","hello"],
  ["hai","hi"],
  ["haos","house"],
  ["haz","him"],
  ["hiirr","here"],
  ["hiiz","his"],
  ["Himil", "March"],
  ["hiz","he"],
  ["hobiz","happy"],
  ["hobisiz","happiness"],
  ["hosi", "use, using"],
  ["hœ","how"],

  ["i","I"],
  ["id","it"],
  ["if","if"],
  ["igso", "jigsaw, puzzle"],
  ["iiti","eight"],
  ["ik","I'm"],
  ["ikonos","economy"],
  ["ikonoset","economic"],
  ["iksban","expand"],
  ["iksit","excite"],
  ["iksitid","excited"],
  ["iksimit","excitement"],
  ["ikt","eat"],
  ["il", "month"],
  ["imii","me, my, myself"],
  ["in","in"],
  ["indizandis","independence (informal)"],
  ["Inland","England"],
  ["Inlish","English"],
  ["innowi","innovation"],
  ["intirnaizono","international"],
  ["is","is"],
  ["ist","is (alt)"],
  ["issra","independent"],
  ["isst","east"],
  ["issranis","independence"],
  ["it","it"],
  ["itimo", "item, object"],
  ["itoldai","yesterday"],
  ["itt","eat"],
  ["iz","its"],

  ["Kabo","Cambodia"],
  ["kal","call"],
  ["kammo","camp"],
  ["kan","night"],
  ["Kanaada","Canada"],
  ["kimistri","chemistry"],
  ["kobkradd","frog"],
  ["kobkradddodd", "frog jump, frog jumping"],
  ["kold","cold"],
  ["kommbotar","computer"],
  ["kommbotat","computation, computational"],
  ["konna","gonna"],
  ["kontinœ","continue"],
  ["kontinœli","continuous"],
  ["kontis","contest"],
  ["korri","curry"],
  ["korrot","correction"],
  ["kostii", "complete, done"],
  ["kœll","cool"],
  ["kœkk", "cook"],
  ["kœkd", "cooked (expression)"],
  ["Kristian","Christian"],
  ["krosi","nearby"],

  ["Laanat", "Mercury"],
  ["labo", "lab, laboratory"],
  ["labonog", "experiment, lab acitivity"],
  ["labt","laptop"],
  ["laii","lie"],
  ["lah","yes"],
  ["lasœksan","congratulations"],
  ["Lapil", "April"],
  ["Lebil", "November"],
  ["liif","life"],
  ["liik","like"],
  ["ligind","legend"],
  ["ligindo","legendary"],
  ["liwisi","revision"],
  ["lo","the (less common)"],
  ["logo", "way, path"],
  ["low","low, little"],
  ["lowin","reduce"],
  ["loz","love"],

  ["maazik","magic"],
  ["maazikal","magical"],
  ["Maditil", "May"],
  ["math","math"],
  ["mathi","mathematical"],
  ["mathi narizbikkolim","prestigious mathematical olympiad"],
  ["mian","mean"],
  ["midt","meet"],
  ["midttaab","meetup"],
  ["midwi","middle"],
  ["midwidai","midday"],
  ["midwikan","midnight"],
  ["mika","cloud"],
  ["milk","milk"],
  ["Minnat", "Moon"],
  ["minnatil", "lunar"],
  ["Mislim","Islam, Muslim"],
  ["mobilfon","smartphone"],
  ["monniz","money"],
  ["mœrnin","morning"],

  ["nai","no, not"],
  ["naifol","divide"],
  ["naigi","negative"],
  ["naiwi","black"],
  ["narizbikk","prestigious"],
  ["narizbikkolim","prestigious contest"],
  ["nasœksan","enjoyable"],
  ["naizon","nation"],
  ["naizono","national"],
  ["NGL","not gonna lie"],
  ["niida","need"],
  ["nidi","subtract"],
  ["niw","new"],
  ["niwbi","newbie"],
  ["NKL","not gonna lie"],
  ["nol","none"],
  ["nott","north"],

  ["ob","up"],
  ["od","old"],
  ["of","of"],
  ["ok","okay"],
  ["okaii","okay"],
  ["Oknil", "October"],
  ["oktaldai","day before yesterday"],
  ["olimmna","Olympics"],
  ["Onat", "Neptune"],
  ["ond","and"],
  ["onil", "pygmy hippo, Moo Deng"],
  ["onn","on"],
  ["orwiti","orbit"],
  ["ot","or"],
  ["otdat", "update"],
  ["otdatid","updated"],
  ["ottimmo","utmost"],

  ["œlog", "journey, long path"],

  ["radi","red"],
  ["radiz","radish"],
  ["rados","radius"],
  ["riliks","relax"],
  ["rilozi","religion"],
  ["rirondai","day after tomorrow"],
  ["Risinat", "Jupiter"],
  ["risti","rest"],
  ["risz","rizz (singular)"],
  ["riiwo","revolve"],
  ["riwisi","revision"],
  ["rizbik","respect"],
  ["robzil","picture"],
  ["rolo", "revert, go back, switch back"],
  ["rondai","tomorrow"],
  ["Rœgil", "June"],
  ["rœla", "nearly"],
  ["rœn","tree"],

  ["Saandai","Sunday"],
  ["Saanat", "Sun"],
  ["sannatal", "solar"],
  ["saats","south"],
  ["sai", "say, tell"],
  ["saio","left"],
  ["salo","right"],
  ["saloz", "really"],
  ["samad","smart"],
  ["samid","summit"],
  ["Satirndai","Saturday"],
  ["saz","her"],
  ["shatin","chatting"],
  ["sid","she"],
  ["siid","hers"],
  ["siiz","science"],
  ["siizi","scientific"],
  ["siiz narizbikk olimmna","prestigious science olympiad"],
  ["sikma","sigma"],
  ["siks","six"],
  ["siks-sion","six seven (slang)"],
  ["Singabora","Singapore"],
  ["sion","seven"],
  ["siro","zero"],
  ["sitmir","statement"],
  ["skœl","school"],
  ["smœna", "common"],
  ["snatz","snatch"],
  ["snazr","snatcher"],
  ["sord","sorry"],
  ["sœitar","super"],
  ["sœksana","merry"],
  ["sœt","should"],
  ["spiz", "speech"],
  ["star","star"],
  ["stato","statue"],
  ["stil","still"],
  ["stillwassir","still water"],
  ["ston","stone"],

  ["tabfon","tablet"],
  ["taizœr siis", "type shii, type shit"],
  ["takk","take"],
  ["tamminno","million"],
  ["tanno","thousand"],
  ["tas", "test"],
  ["tatsa", "text"],
  ["taz","them"],
  ["Thailand","Thailand"],
  ["thikk","thick"],
  ["tishir","teacher"],
  ["ti","yes"],
  ["tiim", "team, group"],
  ["tiiniir", "tired"],
  ["tiiz","theirs"],
  ["tiz","they"],
  ["Tinat", "Mars"],
  ["tirbrik","relieved"],
  ["Tirr","Earth"],
  ["tisti","exam"],
  ["to","to"],
  ["toldai","today"],
  ["translata", "translate"],
  ["tri","three"],

  ["want","want"],
  ["was","what"],
  ["wassir","water"],
  ["watiz", "wait"],
  ["wii","we"],
  ["wiid","wide"],
  ["wiir","wire"],
  ["wiirnai","wireless"],
  ["wik","week"],
  ["wikiin","weekend"],
  ["win","win"],
  ["wirsin","version"],
  ["wisst","west"],
  ["wit","white"],
  ["witt","with"],
  ["wiz","hope"],
  ["wizif","hopeful"],
  ["woi", "why"],
  ["wolo", "world"],
  ["wom", "who"],
  ["won", "when"],
  ["woniit","unite"],
  ["woniiti","unity"],
  ["wor", "where"],
  ["wot", "what (alternative)"],
  ["wœ", "you"],
  ["wœn","one"],

  ["za","yes"],
  ["zaba", "server"],
  ["zad","them (non-binary)"],
  ["zam","charm"],
  ["zas","just"],
  ["zamœl","jamal"],
  ["zamœlin","jamaling"],
  ["Zamœlis","Jamalese"],
  ["zi", "yes"],
  ["Zil", "July"],
  ["zid","they (non-binary)"],
  ["ziid","their (non-binary)"],
  ["zill","chill"],
  ["zilod","yellow"],
  ["Zontil", "January"],
  ["Zozil", "September"]
];
